ip_nas: 192.168.1.200
nfs_server: "{{ ip_nas }}"
nfs_share: /volume1/docker-volumes-{{ env }}
nfs_mount_point: /mnt/nfs
docker_volumes:
  - portainer-data
  - nodered-data
  - homeassistant-config
  - mosquitto-data
  - mosquitto-log
  - mosquitto-config
  - z2mqtt-data
  - z2mqtt-udev
  - ntfy-cache
  - ntfy-user
  - ntfy-data
env: "{{ group_names | difference(['all']) | first }}"