- name: Mettre à jour les dépôts APT
  ansible.builtin.apt:
    update_cache: yes

- name: Installer nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Créer le point de montage local si nécessaire
  ansible.builtin.file:
    path: "{{ nfs_mount_point }}"
    state: directory
    mode: "0755"

- name: Vérifier si le partage NFS est déjà dans /etc/fstab
  ansible.builtin.shell:
    cmd: "grep -q '{{ nfs_mount_point }}' /etc/fstab"
  register: fstab_check
  changed_when: false
  failed_when: fstab_check.rc not in [0, 1]

- name: Ajouter le montage NFS dans /etc/fstab s'il n'est pas déjà présent
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ nfs_server }}:{{ nfs_share }} {{ nfs_mount_point }} nfs defaults,_netdev 0 0"
    state: present
    create: yes
  when: fstab_check.rc != 0
  notify: Remonter les partages NFS

- name: Vérifier si le partage NFS est monté
  ansible.builtin.shell:
    cmd: "mount | grep '{{ nfs_mount_point }}'"
  register: mount_check
  failed_when: mount_check.rc not in [0, 1]
  changed_when: false

- name: Monter le partage NFS si non monté
  ansible.builtin.command:
    cmd: mount -t nfs {{ nfs_server }}:{{ nfs_share }} {{ nfs_mount_point }}
  when: mount_check.rc != 0

- name: Créer les répertoires pour chaque volume dans le partage NFS
  ansible.builtin.file:
    path: "{{ nfs_mount_point }}/{{ item }}"
    state: directory
    mode: "0755"
  with_items: "{{ docker_volumes }}"