- name: Orchestration de déploiement
  hosts: localhost
  tasks:
    - block:
        - name: Exécuter le playbook de clé SSH
          ansible.builtin.include_tasks: 01_deploy-ssh.yml

        - name: Exécuter le playbook de déploiement Docker
          ansible.builtin.include_tasks: 02_deploy-docker.yml
      rescue:
        - name: Échec détecté, effectuer un nettoyage global
          ansible.builtin.debug:
            msg: "Le processus de déploiement a échoué. Nettoyage en cours."
          ansible.builtin.include_tasks: 99_cleanup.yml
          
