- name: Orchestration de déploiement
  hosts: localhost
  tasks:
    - block:
        - name: Exécuter le playbook de clé SSH
          ansible.builtin.import_playbook: 01_deploy-ssh.yml

        - name: Exécuter le playbook de déploiement Docker
          ansible.builtin.import_playbook: 02_deploy-docker.yml
      rescue:
        - name: Échec détecté, effectuer un nettoyage global
          ansible.builtin.import_playbook: 99_cleanup.yml
          
