- name: Docker deployment
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ envName }}.yml"
  tasks:
    - name: Afficher vars
      debug:
        var: vars
    - name: Afficher envName
      debug:
        msg: "group_vars/secret-{{ envName }}.yml"
    - name: Afficher playbook_dir
      debug:
        msg: "La variable playbook_dir est : {{ playbook_dir }}"
    - name: Afficher ansible_private_key
      debug:
        msg: "La variable ansible_private_key est : {{ ansible_private_key }}"


    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: "{{ playbook_dir }}/keys/{{ envName }}-private-key"
        owner: "remi"
        mode: "0600"