- name: Docker deployment
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  tasks:
    - name: Afficher env environnement
      debug:
        msg: "La variable env environnement est : {{ lookup('env', 'env') }}"
    - name: Afficher env
      debug:
        msg: "La variable env est : {{ env }}"
    - name: Afficher envi
      debug:
        msg: "La variable envi est : {{ envi }}"
    - name: Afficher playbook_dir
      debug:
        msg: "La variable playbook_dir est : {{ playbook_dir }}"
    - name: Afficher ansible_private_key
      debug:
        msg: "La variable ansible_private_key est : {{ ansible_private_key }}"
    - name: Afficher group_names
      debug:
        msg: "La variable group_names est : {{ group_names }}"
    - name: Afficher group
      debug:
        msg: "La variable group_names est : {{ group }}"


    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: "{{ playbook_dir }}/keys/{{ env }}-private-key"
        owner: "remi"
        mode: "0600"