- name: Docker deployment
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  become: yes
  vars:
    ansible_become_pass: Z$!JpSyp9wcSxP&oNG7CG*THaMKk
  
  tasks:
    - name: debug env
      ansible.builtin.debug:
        msg: "{{ ansible_become_pass }}"
    - name: show path
      ansible.builtin.debug:
        msg: "{{ playbook_dir }}/{{ env }}-private-key"
    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: "{{ playbook_dir }}/{{ env }}-private-key"
        owner: "remi"
        mode: "0600"

    - name: Mettre à jour le cache des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les clients Mosquitto
      ansible.builtin.apt:
        name: mosquitto-clients
        state: present