- name: Docker deployment
  hosts: localhost
  become: yes
  vars_files:
    - "secrets/localhost.yml"
  
  tasks:

    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ lookup('vars', 'ansible_private_key_' + env) }}"
        dest: "{{ playbook_dir }}/{{ env }}-private-key"
        owner: "remi"
        mode: "0600"

    - name: Mettre à jour le cache des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les clients Mosquitto
      ansible.builtin.apt:
        name: mosquitto-clients
        state: present