- name: Docker deployment
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  tasks:
    - name: Debug des hôtes ciblés
      debug:
        msg: "Hôte actuel : {{ inventory_hostname }}"
    - name: Afficher env
      debug:
        msg: "group_vars/secret-{{ env }}.yml"
    - name: Afficher playbook_dir
      debug:
        msg: "La variable playbook_dir est : {{ playbook_dir }}"

    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: "{{ playbook_dir }}/{{ env }}-private-key"
        owner: "remi"
        mode: "0600"