- name: Docker deployment
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  tasks:
    - name: Afficher la variable d'environnement HOME
      debug:
        - msg: "La variable env est : {{ lookup('env', 'env') }}"
        - msg: "La variable playbook_dir est : {{ lookup('env', 'playbook_dir') }}"
        - msg: "La variable ansible_private_key est : {{ lookup('env', 'ansible_private_key') }}"

    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: "{{ playbook_dir }}/keys/{{ env }}-private-key"
        owner: "remi"
        mode: "0600"