- name: Docker deployment
  hosts: all
  vars_files:
    - "secrets/{{ ENV_NAME }}.yml"
  # become: yes
  # roles:
  #   - role: geerlingguy.docker
 
  tasks:
    - name: display env value
      debug:
        msg: "diff : {{ ENV_NAME }}"
    - name: Afficher toutes les variables disponibles
      debug:
        var:  ansible_become_pass
            # - name: Importer les tâches pour le montage NFS
    #   ansible.builtin.import_tasks: tasks/mount_nfs_nas_docker.yml

    # - name: Vérifier si Docker Compose est installé
    #   ansible.builtin.command:
    #     cmd: docker compose version
    #   ignore_errors: yes
    #   register: docker_compose_installed

    # - name: Installer Docker Compose v2
    #   ansible.builtin.package:
    #     name: docker-compose-plugin
    #     state: present
    #   when: docker_compose_installed.failed

    # - name: Créer le répertoire pour docker-compose
    #   ansible.builtin.file:
    #     path: /opt/docker_app
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: '0755'

    # - name: Générer le fichier docker-compose.yml depuis le template
    #   ansible.builtin.template:
    #     src: templates/docker-compose.yml.j2
    #     dest: /opt/docker_app/docker-compose.yml
    #     owner: root
    #     group: root
    #     mode: "0644"

    # - name: Lancer le docker-compose
    #   ansible.builtin.command:
    #     cmd: docker compose up -d
    #     chdir: /opt/docker_app