- name: Docker deployment
  hosts: all
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  become: yes
  roles:
    - role: geerlingguy.docker
  vars:
    nfs_server: "{{ ip_nas }}"
    nfs_share: /volume1/docker-volumes-{{ env }}
    nfs_mount_point: /mnt/nfs
    nfs_directories:
      - /mnt/nfs/portainer-data
      - /mnt/nfs/nodered-data

  tasks:
    - name: Mettre à jour les dépôts APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Créer le point de montage local si nécessaire
      ansible.builtin.file:
        path: "{{ nfs_mount_point }}"
        state: directory
        mode: "0755"

    - name: Vérifier si le partage NFS est monté
      ansible.builtin.shell:
        cmd: "mount | grep '{{ nfs_mount_point }}'"
      register: mount_check
      failed_when: mount_check.rc not in [0, 1]
      changed_when: false

    - name: Monter le partage NFS si non monté
      ansible.builtin.command:
        cmd: mount -t nfs {{ nfs_server }}:{{ nfs_share }} {{ nfs_mount_point }}
      when: mount_check.rc != 0

    - name: Créer les répertoires pour chaque volume dans le partage NFS
      ansible.builtin.file:
        path: "{{ nfs_mount_point }}/{{ item }}"
        state: directory
        mode: "0755"
      with_items: "{{ docker_volumes }}"

    - name: Vérifier si Docker Compose est installé
      ansible.builtin.command:
        cmd: docker compose version
      ignore_errors: yes
      register: docker_compose_installed

    - name: Installer Docker Compose v2
      ansible.builtin.package:
        name: docker-compose-plugin
        state: present
      when: docker_compose_installed.failed

    - name: Créer le répertoire pour docker-compose
      ansible.builtin.file:
        path: /opt/docker_app
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Générer le fichier docker-compose.yml depuis le template
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: /opt/docker_app/docker-compose.yml
        owner: root
        group: root
        mode: "0644"

    - name: Lancer le docker-compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/docker_app