- name: Docker Home Assistant
  hosts: localhost
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  tasks:
    - name: show path
      ansible.builtin.debug:
        msg: "{{ playbook_dir }}/{{ env }}-private-key"