- name: Docker Mosquitto
  hosts: all
  become: yes
  vars_files:
    - "secrets/{{ inventory_hostname }}.yml"

  tasks:
    - name: Importer les tâches pour le montage NFS
      ansible.builtin.import_tasks: tasks/mount_nfs_nas_docker.yml

    - name: Générer le fichier mosquitto depuis le template
      ansible.builtin.template:
        src: templates/mosquitto/mosquitto.conf.j2
        dest: "{{ nfs_mount_point }}/mosquitto-config/mosquitto.conf"
        backup: yes
        owner: root
        group: root
        mode: "0644"

    - name: Créer le fichier passwd dans le conteneur Mosquitto s'il n'existe pas
      ansible.builtin.command:
        cmd: docker exec mosquitto sh -c "touch /mosquitto/config/pwfile && chmod 600 /mosquitto/config/pwfile"

    - name: Ajouter ou mettre à jour le mot de passe utilisateur dans Mosquitto
      ansible.builtin.command:
        cmd: docker exec mosquitto mosquitto_passwd -b /mosquitto/config/pwfile {{ mosquitto_user }} {{ mosquitto_password }}    
            
    - name: Redémarrer le conteneur Docker mosquitto
      ansible.builtin.command:
        cmd: docker restart mosquitto