- name: Docker Zigbee2mqtt
  hosts: all
  become: yes

  tasks:
    - name: Importer les tâches pour le montage NFS
      ansible.builtin.import_tasks: tasks/mount_nfs_nas_docker.yml

    - name: Générer le fichier configuration.yaml depuis le template
      ansible.builtin.template:
        src: templates/zigbee2mqtt/configuration.yaml.j2
        dest: "{{ nfs_mount_point }}/z2mqtt-data/configuration.yaml"
        backup: yes
        owner: root
        group: root
        mode: "0644"
        
    - name: Redémarrer le conteneur Docker zigbee2mqtt
      ansible.builtin.command:
        cmd: docker restart zigbee2mqtt