- name: Docker Mosquitto
  hosts: all
  vars_files:
    - "group_vars/secret-{{ env }}.yml"
  become: yes

  tasks:
    - name: Importer les tâches pour le montage NFS
      ansible.builtin.import_tasks: tasks/mount_nfs_nas_docker.yml

    - name: Générer le fichier configuration.yaml depuis le template
      ansible.builtin.template:
        src: templates/zigbee2mqtt/configuration.yaml.j2
        dest: "{{ nfs_mount_point }}/mosquitto/configuration-config/configuration.yaml"
        owner: root
        group: root
        mode: "0644"
        
    - name: Redémarrer le conteneur Docker mosquitto
      ansible.builtin.command:
        cmd: docker restart mosquitto