- name: Docker deployment
  hosts: localhost
  tasks:
    - name: Trouver toutes les clés privées
      ansible.builtin.find:
        paths: "{{ playbook_dir }}"
        patterns: "*-private-key"
      register: private_keys

    - name: Supprimer les clés privées trouvées
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ private_keys.files }}"