- name: Docker deployment
  hosts: localhost
  vars_files:
    - secret.yml
  tasks:
    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: ~/.ssh/vm-ansible-100-vm-ubuntu-docker-key
        owner: "{{ ansible_user }}"
        mode: "0600"