- name: Docker deployment
  hosts: vm_test

  tasks:
    - name: Afficher l'utilisateur qui exécute le playbook
      command: whoami
      register: current_user

    - name: Debug  Afficher l'utilisateur
      debug:
        msg: "Le playbook est exécuté par : {{ current_user.stdout }}"