- name: Docker deployment
  hosts: vm_test
  become: yes
  vars_files:
    - secret.yml
  pre_tasks:
    - name: Enregistrer la clé privée
      hosts: localhost
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: ~/.ssh/vm-ansible-100-vm-ubuntu-docker-key
        owner: "{{ ansible_user }}"
        mode: "0600"
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Enregistrer la clé privée
      ansible.builtin.copy:
        content: "{{ ansible_private_key }}"
        dest: ~/.ssh/vm-ansible-100-vm-ubuntu-docker-key
        owner: "{{ ansible_user }}"
        mode: "0600"
    - name: Installer Docker Compose v2
      ansible.builtin.package:
        name: docker-compose-plugin
        state: present

    - name: Créer le répertoire pour docker-compose
      ansible.builtin.file:
        path: /opt/docker_app
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copier le fichier docker-compose.yml
      ansible.builtin.copy:
        src: ../docker/test/docker-compose.yml
        dest: /opt/docker_app/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
        
    - name: Lancer le docker-compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/docker_app