all:
  children:
    test:
      hosts:
        102-vm-ubuntu-docker-test:
          ansible_host: 192.168.1.102
          ansible_user: remi
          ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ env }}-private-key"
    prod:
      hosts:
        100-vm-ubuntu-docker:
          ansible_host: 192.168.1.100
          ansible_user: remi
          ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ env }}-private-key"