name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  Copy-Files:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fournir le mot de passe Vault
        run: echo "${{ secrets.VAULT_PASSWORD }}" > ~/.vault_pass
      - name: run ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/deploy-test.yml --vault-password-file ~/.vault_pass