name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  Copy-Files:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: run ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/deploy-test.yml