name: Test Runner Auto-Hébergé

on:
  push:
    branches:
      - main

jobs:
  Copy-Files:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy files
        run: |
          mkdir -p /home/remi/test
          cp -r README.md /home/remi/test

